export const teamCategories = [
    "Mens Senior",
    "Mens Junior",
    "Womens Senior",
    "Womens Junior",
    "Mens Under 23",
    "Boys Under 19",
    "Boys Under 18",
    "Boys Under 17",
    "Boys Under 16",
    "Boys Under 15",
    "Boys Under 14",
    "Boys Under 13",
    "Boys Under 12",
    "Boys Under 11",
    "Boys Under 10",
    "Boys Under 9",
    "Boys Under 8",
    "Boys Under 6",
    "Girls Under 19",
    "Girls Under 18",
    "Girls Under 17",
    "Girls Under 16",
    "Girls Under 15",
    "Girls Under 14",
    "Girls Under 13",
    "Girls Under 12",
    "Girls Under 11",
    "Girls Under 10",
    "Girls Under 9",
    "Girls Under 8",
    "Girls Under 6",
]

export default teamCategories